apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-springboot-lblqissx
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/sjmrhtap/java-springboot-lblqissx:9c31972cce72849d0dd2d0421f7418f29ee1a76b
          name: container-image
